// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 訂單表
type Order struct {
	// 訂單 ID
	ID string `json:"id"`
	// 訂單狀態 (Created, WaitingForPayment, WaitingForShipment, InTransit, WaitPickup, Completed, Canceled, Refund)
	Status string `json:"status"`
	// 建立時間
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// 更新時間
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// 訂單步驟表（狀態變更歷史）
type OrderStep struct {
	// 步驟 ID
	ID int64 `json:"id"`
	// 訂單 ID（外鍵）
	OrderID string `json:"order_id"`
	// 來源狀態
	FromStatus string `json:"from_status"`
	// 目標狀態
	ToStatus string `json:"to_status"`
	// 建立時間
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
