// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrderStep = `-- name: AddOrderStep :one
INSERT INTO order_steps (
    order_id,
    from_status,
    to_status,
    created_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, order_id, from_status, to_status, created_at
`

type AddOrderStepParams struct {
	OrderID    string           `json:"order_id"`
	FromStatus string           `json:"from_status"`
	ToStatus   string           `json:"to_status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) AddOrderStep(ctx context.Context, arg AddOrderStepParams) (OrderStep, error) {
	row := q.db.QueryRow(ctx, addOrderStep,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.CreatedAt,
	)
	var i OrderStep
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, status, created_at, updated_at
`

type CreateOrderParams struct {
	ID        string           `json:"id"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, status, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderSteps = `-- name: GetOrderSteps :many
SELECT id, order_id, from_status, to_status, created_at FROM order_steps
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetOrderSteps(ctx context.Context, orderID string) ([]OrderStep, error) {
	rows, err := q.db.Query(ctx, getOrderSteps, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderStep{}
	for rows.Next() {
		var i OrderStep
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = $2
WHERE id = $1
RETURNING id, status, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

// 注意：updated_at 由資料庫 trigger 自動更新，無需手動設置
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
