// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateOrderStatus = `-- name: BatchUpdateOrderStatus :exec
UPDATE orders
SET status = $1
WHERE id = ANY($2::text[]) AND status = $3
`

type BatchUpdateOrderStatusParams struct {
	Status   string   `json:"status"`
	Column2  []string `json:"column_2"`
	Status_2 string   `json:"status_2"`
}

// 批量更新訂單狀態（使用 PostgreSQL 的 ANY 操作符）
// 只更新狀態為 fromStatus 的訂單，確保冪等性
func (q *Queries) BatchUpdateOrderStatus(ctx context.Context, arg BatchUpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, batchUpdateOrderStatus, arg.Status, arg.Column2, arg.Status_2)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, status, created_at, updated_at
`

type CreateOrderParams struct {
	ID        string           `json:"id"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, status, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIDForUpdate = `-- name: GetOrderByIDForUpdate :one
SELECT id, status, created_at, updated_at FROM orders
WHERE id = $1
FOR UPDATE NOWAIT
LIMIT 1
`

// 使用悲觀鎖 SELECT FOR UPDATE NOWAIT 避免長時間等待鎖
func (q *Queries) GetOrderByIDForUpdate(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByStatusWithPagination = `-- name: GetOrdersByStatusWithPagination :many
SELECT id, status, created_at, updated_at FROM orders
WHERE status = $1
ORDER BY updated_at ASC
LIMIT $2 OFFSET $3
`

type GetOrdersByStatusWithPaginationParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// 根據狀態獲取訂單列表（支持分頁）
func (q *Queries) GetOrdersByStatusWithPagination(ctx context.Context, arg GetOrdersByStatusWithPaginationParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByStatusWithPagination, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = $2
WHERE id = $1
RETURNING id, status, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

// 注意：updated_at 由資料庫 trigger 自動更新，無需手動設置
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
