// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddOrderStep(ctx context.Context, arg AddOrderStepParams) (OrderStep, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetOrderByID(ctx context.Context, id string) (Order, error)
	GetOrderSteps(ctx context.Context, orderID string) ([]OrderStep, error)
	// 注意：updated_at 由資料庫 trigger 自動更新，無需手動設置
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
